#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "gravitee.io/v1alpha1"
kind: GraviteeServices
metadata:
  name: poc-gw-es-cache
spec:
  enabled: true
  gateway:
    name: gateway-01
    namespace: default
  services:
    elastic-api-cache:
      type: api
# If missing, authentication policy is inherited from the one defined in the GraviteeGateway
#      authentication:
#        policy: key-less
      cors:
        enabled: false
      vhosts:
        - path: "/elastic-cached"
          enabled: true
      resources:
        # resources may be defined at the API level
        local-api-cache:
          resource: cache
          configuration:
            name: "mycache"
            timeToIdleSeconds: 0
            timeToLiveSeconds: 0
            maxEntriesLocalHeap: 0
      paths:
        - prefix: "/*"
          rules:
            - policy:  cache
              configuration:
                # resources defined in GraviteeGateway are inherited by the API
                cacheName: "resource-cache-01.gateway-01.default"
                timeToLiveSeconds: 60
                scope: "API"
            # Policy may be defined in a GraviteePlugin
            - policyReference:
                resource: plugin-01
                name: rate-limit
      endpoints:
        default-group:
          loadBalancing: round-robin
          backendServices:
            - name: elastic-elasticsearch-master
              protocol: HTTP
              port: 9200
              weight: 1